service: serverless-express-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_DIALECT: ${env:DB_DIALECT}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
